import planning.FinEnumFast
import Mathlib.Data.FinEnum
import Mathlib.Data.Fintype.Card
import Mathlib.Logic.Relation
import Mathlib.Tactic

/-!
# Backward closure of a decidable edge relation

The LM-cut heuristic needs two closures of the justification graph: the *goal zone* (the vertices
from which the goal is reachable along zero-cost edges) and plain reachability.  Both were
computed by running one A\* search per vertex, or by repeatedly re-scanning the whole vertex set,
which costs `Θ(|V|³)` edge tests on a graph whose closure takes many rounds (a chain, say).

This module computes such a closure with a breadth-first frontier: each round only follows edges
into the vertices that were *added last*, and only from the vertices that are still unvisited, so
each pair of vertices is examined at most once and the whole closure costs `O(|V|²)` edge tests.

The only interface is `GraphClosure.closure e goal`, together with
`GraphClosure.mem_closure_iff`, which identifies its elements as exactly the vertices from which
`goal` is reachable along `e`-edges (`Relation.ReflTransGen`).
-/

namespace GraphClosure

variable {V : Type} [FinEnum V]

/-- The reachability relation generated by the edge test `e`. -/
abbrev Reach (e : V → V → Bool) (u v : V) : Prop :=
  Relation.ReflTransGen (fun a b => e a b = true) u v

/-- All vertices. -/
def allVerts (V : Type) [FinEnum V] : List V := FinEnum.toList (Finset.univ : Finset V)

lemma mem_allVerts (u : V) : u ∈ allVerts V := by
  simp [allVerts, FinEnum.mem_toList]

/-- All vertices, enumerated directly instead of through the subtype of `Finset.univ`. -/
def allVertsFast (V : Type) [FinEnum V] : List V := FinEnum.toList V

/-- **Enumerating `Finset.univ` is enumerating the type.** -/
@[csimp] theorem allVerts_eq_fast : @allVerts = @allVertsFast := by
  funext V inst
  show (FinEnum.toList {x : V // x ∈ (Finset.univ : Finset V)}).flatMap (fun a => [a.val])
      = FinEnum.toList V
  rw [← toList_univ_subtype V]
  simp [List.flatMap_singleton']

/-- `u` has an edge into the frontier `F`. -/
def hasEdgeTo (e : V → V → Bool) (F : List V) (u : V) : Bool :=
  F.any (fun v => e u v)

lemma hasEdgeTo_iff {e : V → V → Bool} {F : List V} {u : V} :
    hasEdgeTo e F u = true ↔ ∃ v ∈ F, e u v = true := by
  simp [hasEdgeTo]

/-- One breadth-first round: the unvisited vertices with an edge into the frontier. -/
def newVerts (e : V → V → Bool) (F U : List V) : List V :=
  U.filter (hasEdgeTo e F)

/-- The unvisited vertices that stay unvisited. -/
def restVerts (e : V → V → Bool) (F U : List V) : List V :=
  U.filter (fun u => !(hasEdgeTo e F u))

lemma length_newVerts_add (e : V → V → Bool) (F U : List V) :
    (newVerts e F U).length + (restVerts e F U).length = U.length := by
  induction U with
  | nil => simp [newVerts, restVerts]
  | cons a l ih =>
      by_cases h : hasEdgeTo e F a
      · simp [newVerts, restVerts, h, List.filter_cons] at ih ⊢
        omega
      · simp [newVerts, restVerts, h, List.filter_cons] at ih ⊢
        omega

/-- The breadth-first loop: `Z` is what has been found, `F` what was found last, `U` what is
still unvisited. -/
def loop (e : V → V → Bool) : ℕ → List V → List V → List V → List V
  | 0, Z, _, _ => Z
  | k + 1, Z, F, U =>
      let new := newVerts e F U
      if new.isEmpty then Z else loop e k (new ++ Z) new (restVerts e F U)

/-- **The backward closure of `e` from `goal`.** -/
def closure (e : V → V → Bool) (goal : V) : List V :=
  loop e (allVerts V).length [goal] [goal]
    ((allVerts V).filter (fun u => decide (u ≠ goal)))

/-! ### The loop with a caller-supplied frontier step

`newVerts` and `restVerts` test `hasEdgeTo e F u = F.any (e u ·)`, so a round costs one edge
test per pair of an unvisited vertex and a frontier vertex.  A caller that can decide "does
`u` have an edge into `F`" faster — for the justification graph, by one intersection of bit
vectors — can supply the two functions here and still get the same closure
(`closureWith_eq`). -/

/-- The breadth-first loop with the two frontier operations supplied by the caller. -/
def loopWith (e : V → V → Bool) (stepNew stepRest : List V → List V → List V)
    (hnew : ∀ F U, stepNew F U = newVerts e F U)
    (hrest : ∀ F U, stepRest F U = restVerts e F U) :
    ℕ → List V → List V → List V → List V
  | 0, Z, _, _ => Z
  | k + 1, Z, F, U =>
      let new := stepNew F U
      if new.isEmpty then Z
      else loopWith e stepNew stepRest hnew hrest k (new ++ Z) new (stepRest F U)

lemma loopWith_eq (e : V → V → Bool) (stepNew stepRest : List V → List V → List V)
    (hnew : ∀ F U, stepNew F U = newVerts e F U)
    (hrest : ∀ F U, stepRest F U = restVerts e F U) :
    ∀ (k : ℕ) (Z F U : List V), loopWith e stepNew stepRest hnew hrest k Z F U = loop e k Z F U := by
  intro k
  induction k with
  | zero => intro Z F U; rfl
  | succ k ih =>
      intro Z F U
      rw [loopWith, loop, hnew, hrest]
      by_cases h : (newVerts e F U).isEmpty
      · simp [h]
      · simp only [h, Bool.false_eq_true, if_false, ite_false]
        exact ih _ _ _

/-- **The backward closure, with the frontier step supplied by the caller.** -/
def closureWith (e : V → V → Bool) (stepNew stepRest : List V → List V → List V)
    (hnew : ∀ F U, stepNew F U = newVerts e F U)
    (hrest : ∀ F U, stepRest F U = restVerts e F U) (goal : V) : List V :=
  loopWith e stepNew stepRest hnew hrest (allVerts V).length [goal] [goal]
    ((allVerts V).filter (fun u => decide (u ≠ goal)))

/-- The closure does not depend on how the frontier step is computed. -/
theorem closureWith_eq (e : V → V → Bool) (stepNew stepRest : List V → List V → List V)
    (hnew : ∀ F U, stepNew F U = newVerts e F U)
    (hrest : ∀ F U, stepRest F U = restVerts e F U) (goal : V) :
    closureWith e stepNew stepRest hnew hrest goal = closure e goal :=
  loopWith_eq e stepNew stepRest hnew hrest _ _ _ _

/-! ### Soundness -/

lemma loop_sound (e : V → V → Bool) (goal : V) :
    ∀ (k : ℕ) (Z F U : List V), (∀ x ∈ Z, Reach e x goal) → (∀ x ∈ F, Reach e x goal) →
      ∀ x ∈ loop e k Z F U, Reach e x goal := by
  intro k
  induction k with
  | zero => intro Z F U hZ _ x hx; exact hZ x hx
  | succ k ih =>
      intro Z F U hZ hF x hx
      rw [loop] at hx
      by_cases hnew : (newVerts e F U).isEmpty
      · simp only [hnew, if_pos] at hx
        exact hZ x hx
      · simp only [hnew, if_neg, Bool.false_eq_true, ite_false] at hx
        have hnewR : ∀ y ∈ newVerts e F U, Reach e y goal := by
          intro y hy
          rw [newVerts, List.mem_filter] at hy
          obtain ⟨v, hv, hev⟩ := hasEdgeTo_iff.mp hy.2
          exact Relation.ReflTransGen.head hev (hF v hv)
        refine ih (newVerts e F U ++ Z) (newVerts e F U) (restVerts e F U) ?_ hnewR x hx
        intro y hy
        rcases List.mem_append.mp hy with hy | hy
        · exact hnewR y hy
        · exact hZ y hy

/-! ### Completeness -/

/-- The loop only grows `Z`, and it stops with a set that has no incoming edges from outside. -/
lemma loop_closed (e : V → V → Bool) :
    ∀ (k : ℕ) (Z F U : List V), U.length ≤ k →
      (∀ x : V, x ∈ Z ∨ x ∈ U) →
      (∀ u ∈ U, (∃ v ∈ Z, e u v = true) → ∃ v ∈ F, e u v = true) →
      Z ⊆ loop e k Z F U ∧
        ∀ u v : V, v ∈ loop e k Z F U → e u v = true → u ∈ loop e k Z F U := by
  intro k
  induction k with
  | zero =>
      intro Z F U hlen hcov _
      have hU : U = [] := List.eq_nil_of_length_eq_zero (Nat.le_zero.mp hlen)
      subst hU
      refine ⟨by simp [loop], ?_⟩
      intro u v _ _
      rcases hcov u with h | h
      · simpa [loop] using h
      · simp at h
  | succ k ih =>
      intro Z F U hlen hcov hstep
      rw [loop]
      by_cases hnew : (newVerts e F U).isEmpty
      · simp only [hnew, if_pos]
        refine ⟨fun x hx => hx, ?_⟩
        intro u v hv he
        by_contra hu
        rcases hcov u with h | h
        · exact hu h
        · have : ∃ w ∈ F, e u w = true := hstep u h ⟨v, hv, he⟩
          have humem : u ∈ newVerts e F U := by
            rw [newVerts, List.mem_filter]
            exact ⟨h, hasEdgeTo_iff.mpr this⟩
          rw [List.isEmpty_iff] at hnew
          rw [hnew] at humem
          simp at humem
      · simp only [hnew, if_neg, Bool.false_eq_true, ite_false]
        have hne : newVerts e F U ≠ [] := by
          intro h; rw [h] at hnew; simp at hnew
        have hlen' : (restVerts e F U).length ≤ k := by
          have h1 := length_newVerts_add e F U
          have h2 : 0 < (newVerts e F U).length := List.length_pos_of_ne_nil hne
          omega
        have hcov' : ∀ x : V, x ∈ newVerts e F U ++ Z ∨ x ∈ restVerts e F U := by
          intro x
          rcases hcov x with h | h
          · exact Or.inl (List.mem_append.mpr (Or.inr h))
          · by_cases hp : hasEdgeTo e F x
            · exact Or.inl (List.mem_append.mpr (Or.inl (by
                rw [newVerts, List.mem_filter]; exact ⟨h, hp⟩)))
            · exact Or.inr (by
                rw [restVerts, List.mem_filter]
                exact ⟨h, by simp [hp]⟩)
        have hstep' : ∀ u ∈ restVerts e F U,
            (∃ v ∈ newVerts e F U ++ Z, e u v = true) → ∃ v ∈ newVerts e F U, e u v = true := by
          intro u hu ⟨v, hv, he⟩
          rcases List.mem_append.mp hv with hv | hv
          · exact ⟨v, hv, he⟩
          · rw [restVerts, List.mem_filter] at hu
            have hp : hasEdgeTo e F u = true := hasEdgeTo_iff.mpr (hstep u hu.1 ⟨v, hv, he⟩)
            rw [hp] at hu
            simp at hu
        obtain ⟨hsub, hcl⟩ :=
          ih (newVerts e F U ++ Z) (newVerts e F U) (restVerts e F U) hlen' hcov' hstep'
        exact ⟨fun x hx => hsub (List.mem_append.mpr (Or.inr hx)), hcl⟩

/-- **The closure contains exactly the vertices from which `goal` is `e`-reachable.** -/
theorem mem_closure_iff (e : V → V → Bool) (goal u : V) :
    u ∈ closure e goal ↔ Reach e u goal := by
  constructor
  · intro hu
    refine loop_sound e goal _ _ _ _ ?_ ?_ u hu
    · intro x hx; rw [List.mem_singleton] at hx; subst hx; exact Relation.ReflTransGen.refl
    · intro x hx; rw [List.mem_singleton] at hx; subst hx; exact Relation.ReflTransGen.refl
  · intro hu
    have hcov : ∀ x : V, x ∈ [goal] ∨ x ∈ (allVerts V).filter (fun y => decide (y ≠ goal)) := by
      intro x
      by_cases hx : x = goal
      · exact Or.inl (by simp [hx])
      · exact Or.inr (by rw [List.mem_filter]; exact ⟨mem_allVerts x, by simp [hx]⟩)
    have hlen : ((allVerts V).filter (fun y => decide (y ≠ goal))).length ≤ (allVerts V).length :=
      List.length_filter_le _ _
    obtain ⟨hsub, hcl⟩ :=
      loop_closed e (allVerts V).length [goal] [goal]
        ((allVerts V).filter (fun y => decide (y ≠ goal))) hlen hcov (by
          intro x _ h; exact h)
    have hgoal : goal ∈ closure e goal := hsub (by simp)
    induction hu using Relation.ReflTransGen.head_induction_on with
    | refl => exact hgoal
    | head hab _ ih => exact hcl _ _ ih hab

end GraphClosure
