name = "planlib"
version = "0.1.0"
defaultTargets = ["planlib", "planner"]

[[lean_lib]]
name = "planlib"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "unplanvalidator"
git = "https://github.com/AmosNico/validator"
rev = "v4.27.0"

[[require]]
name = "SearchAlgorithms"
git = "https://github.com/galvusdamor/lean4-search-algorithms"
rev = "v4.27.0"

[[lean_exe]]
name = "planner"
root = "Planner.Main"
