name = "graphlib"
version = "0.1.0"
defaultTargets = ["graphlib"]

[[lean_lib]]
name = "Graphlib"

[[lean_exe]]
name = "graphlib"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"